### ISSUE TITLE
Error during HEAR Embedding computation

### ISSUE THREAD

**Issue by alexanderwerning** [nttcslab/msm-mae#1]
Hello, I tried to reproduce the results on the HEAR Benchmark using one of the pretrained models (`80x512p16x16_0425`).
When computing the embeddings (`python -m heareval.embeddings.runner ...`), an error occurred:
```
Traceback (most recent call last):
  File ".../python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File ".../lib/python3.8/site-packages/heareval/embeddings/runner.py", line 137, in <module>
    runner()
  File ".../lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".../lib/python3.8/site-packages/heareval/embeddings/runner.py", line 112, in runner
    task_embeddings(embedding, task_path, embed_task_dir)
  File ".../lib/python3.8/site-packages/heareval/embeddings/task_embeddings.py", line 446, in task_embeddings
    embeddings = embedding.get_scene_embedding_as_numpy(audios)
  File ".../lib/python3.8/site-packages/heareval/embeddings/task_embeddings.py", line 132, in get_scene_embedding_as_numpy
    embeddings = self.module.get_scene_embeddings(  # type: ignore
  File ".../msm-mae/hear/hear_msm/pretrained_model_msm_mae_80x512p16x16_0425.py", line 26, in get_scene_embeddings
    return model.get_scene_embeddings(audio)
  File ".../msm-mae/hear/hear_msm/msm_mae/runtime.py", line 193, in get_scene_embeddings
    x = self.encode(audio)
  File ".../msm-mae/hear/hear_msm/msm_mae/runtime.py", line 184, in encode
    x = self.to_normalized_spec(batch_audio)
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RuntimeMAE' object has no attribute 'to_normalized_spec'
```

I could not find any function `to_normalized_spec` in the code, so I replaced the call to `to_normalized_spec` with `to_feature`, which should compute the spectrogram and normalize it?

Is this an error in the code or am I missing something?
Thank you!

**Comment by daisukelab** [comment]
Hi @alexanderwerning,

Thank you for your report. It's a bug, and I fixed it with https://github.com/nttcslab/msm-mae/commit/11fcc4280c6e6e9a6b2d22a2599b664f8e82668a
.

In the previous commit, I have removed the `to_normalized_spec` accidentally, which was recovered now.

Thanks again for your interest.
Please let me know if you need anything else.

**Comment by alexanderwerning** [comment]
Thank you!
